dist: focal

language: ruby

cache:
  - bundler
  - yarn

before_install:
  - nvm install --lts

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - rake assets:precompile

script:
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
